version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nl_gym
      MYSQL_USER: KyNhat
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: gym_backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nl_gym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: KyNhat
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"

volumes:
  mysql_data:
