spring.application.name=NL_Gym
spring.datasource.url=jdbc:mysql://localhost:3306/nl_gym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=KyNhat
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none  
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true  
logging.level.org.springframework.security=DEBUG
spring.main.allow-bean-definition-overriding=true
System.out.println(">>> Authentication Principal: " + authentication.getPrincipal().getClass().getName());



# Cho phép upload file l?n h?n (tùy ch?nh kích th??c theo nhu c?u)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

upload.path=D:/java_proj/NL_Gym/uploads/
spring.mvc.static-path-pattern=/api/avatar/**
spring.web.resources.static-locations=file:uploads/avatars
